# PostgreSQL. Versions 9.1 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stack_overflow_development

test:
  <<: *default
  database: stack_overflow_test

#
production:
  <<: *default
  database: stack_overflow_production
  username: stack_overflow
  password: <%= ENV['STACK_OVERFLOW_DATABASE_PASSWORD'] %>
